### ISSUE TITLE
Unneeded dependencies in requirements.freeze.txt?

### ISSUE THREAD

**Issue by mcbanderson** [reflexivesecurity/reflex-cli#119]
There are some dependencies listed in there that I don't think we need. If that is indeed the case we should remove dependencies we don't actually need.

**Comment by rot26** [comment]
For example: `black` is a developer dependency.  We don't really need that as part of the main `requirements.txt`

**Comment by rot26** [comment]
I've really liked using [pip-tools](https://github.com/jazzband/pip-tools) for managing python lock files (if I'm not already locked into `pipenv`)  @mcbanderson Thoughts?

**Comment by mcbanderson** [comment]
I don't really have a strong preference as to whether we use `pip-tools`, `pipenv`, `poetry`, or whatever.

Beyond just separating dev/prod dependencies like `black` though, there are dependencies in `requirements.freeze.txt` that I suspect we don't need at all, and were never intended to be included. For example `PyJWT` is included as a dependency, and to my knowledge we aren't using JWTs anywhere in the project. I suspect the freeze file was generated outside of a virtualenv which resulted in some of these extraneous packages being included. My intention with this issue was to identify which (if any) of these dependencies are actually extraneous and remove them.
