### ISSUE TITLE
Reflex Init non-interactive fails when it encounters a rule refactored for multi region.

### ISSUE THREAD

**Issue by MikeSchapp** [reflexivesecurity/reflex-cli#138]
At current `reflex init` will fail when it encounters reflex-aws-ebs-public-snapshot. Will need to update the logic to handle the new directory structure of each rule.

**Comment by rjulian** [comment]
Hey @MikeSchapp can you reproduce this still or provide steps to reproduce? If not, can you close this as I think we have fixed this.

**Comment by mcbanderson** [comment]
I believe this is fixed, so closing. If this is still an issue feel free to reopen.
