### ISSUE TITLE
Early abortion of reflex package leaves behind temp directory and fails future package

### ISSUE THREAD

**Issue by rjulian** [reflexivesecurity/reflex-cli#237]
When running `reflex package` and hitting CTRL+C, it causes the packaging operation to stop and finish in a broken state. 

When running `reflex package` after failed invocation, it generates: `FileExistsError: [Errno 17] File exists: 'temp/package'`
`

**Comment by mcbanderson** [comment]
Looks like we can use `tempfile` to fix this

https://docs.python.org/3/library/tempfile.html
